# Jekyll
markdown: rdiscount
highlighter: "pygments"
permalink: /:title.html

# Conference info
conf:
  name: "Barcode"
  description: "Barcode é um evento criado para que profissionais da área de TI possam ficar longe do teclado por um tempo, beber cerveja, assistir palestras curtas e, claro, trocar aquele bom papo nerd."
  date: "31 de julho"
  price: "Free"
  address: "Av. Ivo do Prado, 734 - São José"
  venue: "Estado da Arte Café"
  city: "Aracaju"

# Site info
site:
  url: "http://barcode.gdgaracaju.com.br"
  favicon: "http://site.gdgaracaju.com.br/favicon.png"
  googleanalytics: "UA-33656081-1"
  images:
    cover: "http://f.cl.ly/items/2X28422q1e3w0C2U1P3H/866591_24254643.jpg"
    facebook: "http://braziljs.org/img/fb-share.jpg"

subscribe_text: "Inscreva-se"
subscribe_url: "https://plus.google.com/events/cu0u99msvd8e05sus6gefipe078"

# Active sections on the website
sections:
  about: true
  c4p: true
  location: true
  speakers: true
  schedule: true
  sponsors: true
  partners: true
  contact: false

# The entire schedule
schedule:
  -
    name: "Chegada sóbria :)"
    time: "18h00"
  -
    name: "Thiago Guimarães"
    photo: "img/thiago-guimaraes.jpg"
    bio: "Formado em técnico pelo IFS, quinto período em Sistemas de Informação na UNIT, trabalho programação a 6 anos passando pelas linguagens PHP, Java, C# e Ruby, além de desenvolvimento frontend HTML, CSS e JS. Hoje sou colaborador da Jaya Apps, empresa de SP que presta consultoria para empresas. Trabalhamos com a linguagem Ruby, Java e o framework Ruby on Rails, utilizando banco de dados MySQL, PostgreSQL e MongoDB. Já trabalhei para 3 empresas de Aracaju/SE, uma de Cleveland/OH (USA) e hoje trabalho para uma de São Paulo/SP."
    company: "Jaya Apps - Peão"
    socials:
      -
        service: "github"
        handler: "thiagogsr"
      -
        service: "twitter"
        handler: "thiagogsr"
      -
        service: "facebook"
        handler: "thiagogsr"
    presentation:
      title: "Ruby para Javeiros"
      description: "Vamos comparar código Java com código Ruby? Leve um lenço :)"
      time: "18h00"
  -
    name: "Diego Melo"
    photo: "img/diego-melo.jpg"
    bio: "Entusiasta em Linux desde os 14 anos, desenvolvedor a mais de 3 anos, gamer casual, UI e UX entusiasta e sempre buscando novas maneiras de melhorar e otimizar a forma de desenvolvimento dos projetos."
    company: "Unit - Desenvolvedor"
    socials:
      -
        service: "github"
        handler: "diegomelo182"
      -
        service: "facebook"
        handler: "diego.melo.370"
    presentation:
      title: "Usando pre-processadores no desenvolvimento front-end"
      description: "Como fazer uma aplicação web de forma otimizada e simplificada para dispositivos mobile e PCs com Sass."
      time: "19h30"

# List of Sponsors
sponsors:
  -
    name: "GDG Aracaju"
    logo: "http://f.cl.ly/items/1U3p0Z0e2w0I1i3z1X22/Image%202012.09.25%203:00:58%20PM.png"
    url: "http://eventick.com.br"

# List of Partners
partners:
  -
    name: "Popcode"
    logo: "http://f.cl.ly/items/2N3i2W0X2f3c2g2Z2N0f/Untitled-1.png"
    url: "http://braziljs.org"

# About section
about_section:
   title: "Sobre"
   description:
    -
      p: "Barcode é um evento criado para que profissionais da área de TI possam ficar longe do teclado por um tempo, beber cerveja, assistir palestras curtas e, claro, trocar aquele bom papo nerd."
    -
      p: "Quer falar sobre Android, iOS, Ruby, Python, Javascript, Node, Go, C#, PHP, Java, Scala, Scrum, Design etc? Venha para o evento, pegue uma cerveja (ou café, água...) e mãos na massa!"

# Call for papers section
c4p_section:
   title: "Call for papers"
   text: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat."
   c4p_url: "http://call4paperz.com"
   c4p_caption: "Submit"
   c4p_rules_url: "http://call4paperz.com"
   c4p_rules_caption: "Read the rules."

# Contact section
contact_section:
   title: "Contact"
   text: "Contact us if you have any questions."
   contacts:
   -
     title: "Email"
     link: "mailto:your_email@domain"
   -
     title: "Facebook"
     link: "https://www.facebook.com/yourpage"
   email: "your_email@domain"
   twitter_url: "http://twitter.com/your_twitter"
   twitter_username: "@your_twitter"
   show_form: false
   form:
    action: "contato.php"
    name: "What's your name?"
    email: "What's your email?"
    message: "Write a message"
    send_button: "Send"

# Location section
location_section:
   title: "Local"

# Partners section
partners_section:
   title: "Parceiros"
   show_your_logo_here: true

# Schedule section
schedule_section:
   title: "Agenda"
   text: "A agenda pode ser alterada sem aviso prévio."
   time: "Hora"
   slot: "Slot"
   description: "Descrição"

# Speakers section
speakers_section:
   title: "Palestrantes"

# Sponsors section
sponsors_section:
   title: "Patrocinadores"
   show_your_logo_here: true
