# Jekyll
markdown: rdiscount
highlighter: "pygments"
permalink: /:title.html

# Conference info
conf:
  name: "Barcode"
  description: "Barcode é um evento criado para que profissionais da área de TI possam ficar longe do teclado por um tempo, beber cerveja, assistir palestras curtas e, claro, trocar aquele bom papo nerd."
  date: "13 de novembro"
  price: "Free"
  address: "Rua Américo Curvelo, 585 - Grageru"
  venue: "Garage 585"
  city: "Aracaju"

# Site info
site:
  url: "http://barcode.gdgaracaju.com.br"
  favicon: "http://site.gdgaracaju.com.br/favicon.png"
  googleanalytics: "UA-33656081-1"
  images:
    cover: "http://f.cl.ly/items/2X28422q1e3w0C2U1P3H/866591_24254643.jpg"
    facebook: "http://barcode.gdgaracaju.com.br/img/facebook-thumb.jpg"

subscribe_text: "Participe"
subscribe_url: "https://goo.gl/9nwgho"

# Active sections on the website
sections:
  about: true
  c4p: true
  location: true
  speakers: true
  schedule: false
  sponsors: false
  partners: false
  contact: false

# The entire schedule
schedule:
  -
    name: "Chegada sóbria :)"
    time: "18h00"
  -
    name: "Diego Melo"
    photo: "img/diego-melo.jpg"
    bio: "Entusiasta em Linux desde os 14 anos, desenvolvedor a mais de 3 anos, gamer casual, UI e UX entusiasta e sempre buscando novas maneiras de melhorar e otimizar a forma de desenvolvimento dos projetos."
    company: "Unit - Desenvolvedor"
    socials:
      -
        service: "github"
        handler: "diegomelo182"
      -
        service: "facebook"
        handler: "diego.melo.370"
    presentation:
      title: "Ruby on Rails e REST API"
      description: ""
      time: "19h00"
  -
    name: "Italo Santos"
    photo: "img/italo-santos.jpg"
    bio: "Desenvolvedor Front End por acaso, encontrou sua paixão em AngularJS e JavaScript. Faz parte da Infonet há mais de 5 anos e hoje atua na Inventione, empresa parceira de projetos de inovação. Também é responsável por guiar a equipe de desenvolvedores da Softeam."
    company: "Infonet"
    socials:
      -
        service: "facebook"
        handler: "italosnt"
      -
        service: "linkedin"
        handler: "italosnt"
    presentation:
      title: "Greetings, AngularJS"
      description: ""
      time: "20h30"

# List of Sponsors
sponsors:
  -
    name: "GDG Aracaju"
    logo: "http://f.cl.ly/items/1U3p0Z0e2w0I1i3z1X22/Image%202012.09.25%203:00:58%20PM.png"
    url: "http://eventick.com.br"

# List of Partners
partners:
  -
    name: "Popcode"
    logo: "http://f.cl.ly/items/2N3i2W0X2f3c2g2Z2N0f/Untitled-1.png"
    url: "http://braziljs.org"

# About section
about_section:
   title: "Sobre"
   description:
    -
      p: "BarCode é um evento criado para que profissionais da área de TI possam ficar longe do teclado por um tempo, beber cerveja, assistir palestras curtas e, claro, trocar aquele bom papo nerd."
    -
      p: "Quer falar sobre Android, iOS, Ruby, Python, Javascript, Node, Go, C#, PHP, Java, Scala, Scrum, Design etc? Venha para o evento, pegue uma cerveja (ou café, água...) e mãos na massa!"

# Call for papers section
c4p_section:
   title: "Call for papers"
   text: "Quer palestrar?"
   c4p_url: "https://goo.gl/QuHXj7"
   c4p_caption: "Faça uma proposta"
   c4p_rules_url: ""
   c4p_rules_caption: ""

# Contact section
contact_section:
   title: "Contact"
   text: "Contact us if you have any questions."
   contacts:
   -
     title: "Email"
     link: "mailto:your_email@domain"
   -
     title: "Facebook"
     link: "https://www.facebook.com/yourpage"
   email: "your_email@domain"
   twitter_url: "http://twitter.com/your_twitter"
   twitter_username: "@your_twitter"
   show_form: false
   form:
    action: "contato.php"
    name: "What's your name?"
    email: "What's your email?"
    message: "Write a message"
    send_button: "Send"

# Location section
location_section:
   title: "Local"

# Partners section
partners_section:
   title: "Parceiros"
   show_your_logo_here: true

# Schedule section
schedule_section:
   title: "Agenda"
   text: "A agenda pode ser alterada sem aviso prévio."
   time: "Hora"
   slot: "Slot"
   description: "Descrição"

# Speakers section
speakers_section:
   title: "Palestrantes"

# Sponsors section
sponsors_section:
   title: "Patrocinadores"
   show_your_logo_here: true
